backend:
  name: github
  repo: guyi2298/leishen
  branch: main
  base_url: /leishen

media_folder: static/images/uploads
public_folder: /leishen/images/uploads

i18n:
  structure: multiple_folders
  locales: [en, zh, vi, id, th, ms]
  default_locale: en

collections:
  - name: home
    label: Home
    folder: content
    i18n: true
    create: false
    delete: false
    slug: _index
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: products
    label: Products
    folder: content
    i18n: true
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Image, name: image, widget: image, required: false }
      - { label: Body, name: body, widget: markdown }

  - name: cases
    label: Cases
    folder: content
    i18n: true
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: about
    label: About
    folder: content
    i18n: true
    create: false
    delete: false
    slug: _index
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: contact
    label: Contact
    folder: content
    i18n: true
    create: false
    delete: false
    slug: _index
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: posts
    label: Posts
    folder: content
    i18n: true
    create: true
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: string }
      - { label: Body, name: body, widget: markdown }
